global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
alerting:
    alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v1
      static_configs:
      - targets: []
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']
  - job_name: nginx
    metrics_path: /
    static_configs:
    - targets: ['host.docker.internal:8090']
  